apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: sidecar-web-app
    labels:
      pattern: sidecar
  spec:
    containers:
    - name: main-app
      image: centos/httpd
      ports:
        - containerPort: 80
      volumeMounts:
      - mountPath: /var/www/html
        name: git
    - name: sidecar-polling-repo
      image: axeclbr/git
      volumeMounts:
      - mountPath: /var/lib/data
        name: git
      env:
        - name: GIT_REPO
          value: https://github.com/rhuss/beginner-html-site-scripted
      command:
      - "sh"
      - "-c"
      - "git clone $(GIT_REPO) . && watch -n 60 git pull"
      workingDir: /var/lib/data
    volumes:
    - emptyDir: {}
      name: git
